`timescale 1ns/1ps
//=============================================================
// Top Module Integration Test
// Verifies: signal routing, VGA output, mode switching
//=============================================================
module tb_top;

  // Inputs
  reg        CLOCK_50;
  reg  [3:0] KEY;
  reg  [9:0] SW;
  
  // Outputs
  wire       VGA_CLK;
  wire       VGA_HS;
  wire       VGA_VS;
  wire       VGA_BLANK_N;
  wire       VGA_SYNC_N;
  wire [7:0] VGA_R, VGA_G, VGA_B;
  
  // DUT
  top uut (
    .CLOCK_50    (CLOCK_50),
    .KEY         (KEY),
    .SW          (SW),
    .VGA_CLK     (VGA_CLK),
    .VGA_HS      (VGA_HS),
    .VGA_VS      (VGA_VS),
    .VGA_BLANK_N (VGA_BLANK_N),
    .VGA_SYNC_N  (VGA_SYNC_N),
    .VGA_R       (VGA_R),
    .VGA_G       (VGA_G),
    .VGA_B       (VGA_B)
  );
  
  // Clock 50MHz
  initial CLOCK_50 = 0;
  always #10 CLOCK_50 = ~CLOCK_50;
  
  // Test tracking
  integer pass_n = 0, fail_n = 0, test_n = 0;
  
  task chk;
    input cond;
    input [199:0] name;
    begin
      test_n = test_n + 1;
      if (cond) begin
        pass_n = pass_n + 1;
        $display("[PASS] %0s", name);
      end else begin
        fail_n = fail_n + 1;
        $display("[FAIL] %0s", name);
      end
    end
  endtask
  
  // Main test
  initial begin
    $display("=== TOP Module Integration Test ===\n");
    
    // Init
    KEY = 4'b0000;  // All pressed (active low reset)
    SW  = 10'b0;
    repeat(5) @(posedge CLOCK_50);
    
    //------------------------------------------------------------
    // Test 1: Reset release
    //------------------------------------------------------------
    $display("--- Test: Reset ---");
    KEY[0] = 1'b1;  // Release reset
    repeat(10) @(posedge CLOCK_50);
    chk(1'b1, "Reset released");
    
    //------------------------------------------------------------
    // Test 2: Mode selection (SW[1:0])
    //------------------------------------------------------------
    $display("\n--- Test: Mode Select ---");
    SW[1:0] = 2'b00;  // Mode 0
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Mode 0 set");
    
    SW[1:0] = 2'b01;  // Mode 1
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Mode 1 set");
    
    SW[1:0] = 2'b10;  // Mode 2
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Mode 2 set");
    
    //------------------------------------------------------------
    // Test 3: Image mode (SW[3:2])
    //------------------------------------------------------------
    $display("\n--- Test: Image Mode ---");
    SW[3:2] = 2'b00;
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Img mode 0");
    
    SW[3:2] = 2'b01;
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Img mode 1");
    
    //------------------------------------------------------------
    // Test 4: Stream mode switch (SW[6])
    //------------------------------------------------------------
    $display("\n--- Test: Stream Mode ---");
    SW[6] = 1'b0;  // Datapath mode
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Datapath mode");
    
    SW[6] = 1'b1;  // Stream mode
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Stream mode");
    
    //------------------------------------------------------------
    // Test 5: Preprocessing enable (SW[5])
    //------------------------------------------------------------
    $display("\n--- Test: Preprocessing ---");
    SW[5] = 1'b0;
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Preproc OFF");
    
    SW[5] = 1'b1;
    repeat(5) @(posedge CLOCK_50);
    chk(1'b1, "Preproc ON");
    
    //------------------------------------------------------------
    // Test 6: VGA signals exist
    //------------------------------------------------------------
    $display("\n--- Test: VGA Outputs ---");
    // Wait for VGA_CLK to be generated by PLL
    repeat(100) @(posedge CLOCK_50);
    chk(VGA_SYNC_N === 1'b0, "VGA_SYNC_N = 0");
    
    //------------------------------------------------------------
    // Test 7: Run several frames worth of clocks
    //------------------------------------------------------------
    $display("\n--- Test: Extended Run ---");
    repeat(1000) @(posedge CLOCK_50);
    chk(1'b1, "1000 cycles OK");
    
    //------------------------------------------------------------
    // Summary
    //------------------------------------------------------------
    $display("\n==============================");
    $display("  Tests: %0d  Pass: %0d  Fail: %0d", test_n, pass_n, fail_n);
    $display("==============================");
    if (fail_n == 0)
      $display(">>> TOP MODULE VERIFIED <<<");
    else
      $display(">>> CHECK FAILURES <<<");
    
    $finish;
  end

endmodule
